weights: yolov5s.pt
cfg: ''
data: /imatge/ebayo/TFM/MOB-DDBB/db_a_55img_3c_split/dataset.yaml
hyp: data/hyp.finetune_DA2.yaml
epochs: 100
batch_size: 18
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: yolov5_ts_detect
name: exp
exist_ok: false
quad: false
world_size: 1
global_rank: -1
save_dir: yolov5_ts_detect/exp
total_batch_size: 18
